public enum AppStrings {
    public enum Pages {
        public static let overview = "总览"
        public static let agents = "Agent"
        public static let usageCenter = "用量中心"
        public static let connection = "连接"
        public static let settings = "设置"
        public static let about = "关于"
    }

    public enum Metrics {
        public static let todayTokens = "今日 Token"
        public static let weekTokens = "本周 Token"
        public static let monthTokens = "本月 Token"
        public static let todayCost = "今日花费"
        public static let weekCost = "本周花费"
        public static let monthCost = "本月花费"
        public static let averageDailyCost = "平均每日花费"
        public static let todayActiveTime = "今日活跃时长"
        public static let todaySessions = "今日会话数"
        public static let averageSessionLength = "平均会话时长"
        public static let peakHour = "活跃高峰时段"
        public static let peakDay = "本周高峰日"
    }

    public enum Sections {
        public static let usageCenter = "用量中心"
        public static let agentJournal = "Agent 日志"
        public static let tokenBreakdown = "Token 结构"
    }

    public enum Diagnostics {
        public static let title = "AgentPulse 诊断"
        public static let monitoringPaused = "监控暂停"
        public static let floatingWindow = "悬浮窗"
        public static let codexEnabled = "Codex 监控"
        public static let codexStatus = "Codex 状态"
        public static let codexStatusReason = "Codex 状态来源"
        public static let codexStatusAge = "Codex 状态时效"
        public static let currentSignal = "当前状态"
        public static let previousSignal = "上一状态"
        public static let lastActiveSignal = "最近活跃状态"
        public static let lastRefresh = "最近刷新"
        public static let sessionMergeWindow = "Session 合并窗口"
        public static let lastSessionActivity = "最近 Session 活动"
        public static let willCreateNewSession = "下一次是否新建 Session"
        public static let sessionCreateReason = "Session Create Reason"
        public static let currentSessionStartedAt = "当前会话开始时间"
        public static let todayActiveTime = "今日活跃时长"
        public static let todaySessions = "今日会话数"
        public static let lastActiveIncrement = "最近活跃增量"
        public static let todayTokens = "今日 Token"
        public static let thirtyDayTokens = "近 30 天 Token"
        public static let recentDailyTokens = "最近每日 Token"
        public static let usageScannedAt = "用量扫描时间"
        public static let tokenBreakdown = "Token 结构"
        public static let tokenSource = "Token 来源"
        public static let costSource = "花费来源"
        public static let quotaSource = "剩余额度来源"
        public static let topModels = "主要模型"
        public static let toolStats = "工具调用"
        public static let quota5hRemaining = "5 小时剩余额度"
        public static let quota5hReset = "5 小时重置时间"
        public static let weekQuotaRemaining = "本周剩余额度"
        public static let weekQuotaReset = "本周重置时间"
        public static let quotaLastError = "剩余额度最近错误"
        public static let cachedUsageFiles = "缓存用量文件"
        public static let scannedUsageFiles = "已扫描用量文件"
        public static let latestSession = "最新会话"
        public static let latestSessionModified = "最新会话更新时间"
        public static let usageCacheSchema = "用量缓存版本"
        public static let stateFile = "状态文件"
        public static let settingsFile = "设置文件"
        public static let usageCache = "用量缓存"
        public static let codexSessions = "Codex 会话目录"
        public static let unknown = "未知"
        public static let none = "无"
    }
}
